### ISSUE TITLE
WindowHeaderExtensionConnector uses non-camelcase CSS property name

### ISSUE THREAD

**Issue by Wnt** [KatriHaapalinna/window-header-extension#1]
The call on line
https://github.com/KatriHaapalinna/window-header-extension/blob/91a3c1acce6c7da3b975120f561c9245b286d836/src/main/java/org/vaadin/addons/windowheaderextension/client/WindowHeaderExtensionConnector.java#L80
will cause an assertion failure in Style as it uses a non-camel case CSS property name.

**Comment by KatriHaapalinna** [comment]
Fixed in versions 1.1 and 2.0

**Comment by KatriHaapalinna** [comment]
Fixed in versions 1.1 and 2.0
